package com.coder_x.connect

object QuotesList {
    var englishQuotes = listOf(
        "Believe you can and you're halfway there.",
        "Dream big, work hard.",
        "Stay positive, work hard, make it happen.",
        "Success is not for the lazy.",
        "Push yourself because no one else is going to do it for you.",
        "Be fearless in the pursuit of what sets your soul on fire.",
        "Great things never come from comfort zones.",
        "Do something today that your future self will thank you for.",
        "Work hard in silence, let success be your noise.",
        "Focus on the step in front of you, not the whole staircase.",
        "Don't stop when you're tired, stop when you're done.",
        "Make each day your masterpiece.",
        "You are stronger than you think.",
        "Do what you love, love what you do.",
        "Your only limit is your mind.",
        "Believe in yourself and all that you are.",
        "Hard work beats talent when talent doesn't work hard.",
        "Start where you are, use what you have, do what you can.",
        "Success is a series of small wins.",
        "Every day is a second chance.",
        "The best time to plant a tree was 20 years ago. The second best time is now.",
        "Dream it. Wish it. Do it.",
        "Great things take time.",
        "You don’t have to be great to start, but you have to start to be great.",
        "Turn your dreams into plans.",
        "Stay committed to your decisions, but stay flexible in your approach.",
        "Small steps in the right direction can turn out to be the biggest step of your life.",
        "Focus on the good.",
        "Be the energy you want to attract.",
        "Every moment is a fresh beginning.",
        "Make today so awesome that yesterday gets jealous.",
        "Don't wait for opportunity. Create it.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream it. Do it. Repeat.",
        "Do it with passion or not at all.",
        "Be the change you wish to see in the world.",
        "Success is not just about making money, it's about making a difference.",
        "You are capable of amazing things.",
        "Stay patient and trust your journey.",
        "Your future is created by what you do today, not tomorrow.",
        "Dream big. Start small. Act now.",
        "Make it happen. Shock everyone.",
        "You don’t find the happy life. You make it.",
        "Push yourself because no one else is going to do it for you.",
        "Believe you can and you're halfway there.",
        "The best way to predict the future is to create it.",
        "You are your only limit.",
        "Stay focused and never give up.",
        "Great things never come from comfort zones.",
        "Your potential is endless."
    )

    var arabicQuotes = listOf(
        "لا تدع أحداً يطفئ النور في قلبك.",
        "ابدأ من حيث أنت، استخدم ما لديك، وافعل ما تستطيع.",
        "السعادة ليست في امتلاك كل شيء، بل في الشعور بالرضا عن كل شيء.",
        "كل يوم هو فرصة جديدة لبداية جديدة.",
        "لا تيأس، فربما أجمل أيام حياتك لم تأتِ بعد.",
        "اجعل كل يوم تحفة فنية.",
        "أنت أقوى مما تعتقد.",
        "افعل ما تحب، وأحب ما تفعل.",
        "حدك الوحيد هو عقلك.",
        "آمن بنفسك وبكل ما أنت عليه.",
        "العمل الجاد يتغلب على الموهبة عندما لا يعمل صاحب الموهبة بجد.",
        "النجاح سلسلة من الانتصارات الصغيرة.",
        "أفضل وقت لزراعة شجرة كان قبل 20 عامًا، وثاني أفضل وقت هو الآن.",
        "احلم بها، تمنّها، افعلها.",
        "الأشياء العظيمة تستغرق وقتًا.",
        "لست مضطرًا لأن تكون عظيمًا لتبدأ، لكن عليك أن تبدأ لتكون عظيمًا.",
        "حوّل أحلامك إلى خطط.",
        "كن ملتزمًا بقراراتك، لكن كن مرنًا في نهجك.",
        "الخطوات الصغيرة في الاتجاه الصحيح قد تتحول إلى أكبر خطوة في حياتك.",
        "ركّز على الخير.",
        "كن الطاقة التي تريد أن تجذبها.",
        "كل لحظة هي بداية جديدة.",
        "اجعل اليوم رائعًا لدرجة أن يغار الأمس.",
        "لا تنتظر الفرصة، اصنعها.",
        "كلما عملت بجد من أجل شيء ما، زاد شعورك بالروعة عندما تحققه.",
        "احلم بها، افعلها، كررها.",
        "افعلها بشغف أو لا تفعلها أبدًا.",
        "كن التغيير الذي تريد أن تراه في العالم.",
        "النجاح لا يقتصر على كسب المال فقط، بل يتعلق بإحداث فرق.",
        "أنت قادر على فعل أشياء مذهلة.",
        "كن صبورًا وثق برحلتك.",
        "مستقبلك يصنعه ما تفعله اليوم، وليس غدًا.",
        "احلم كبيرًا، ابدأ صغيرًا، تحرك الآن.",
        "حققها، افاجئ الجميع.",
        "لا تجد الحياة السعيدة، بل تصنعها.",
        "ادفع نفسك لأن لا أحد آخر سيفعل ذلك من أجلك.",
        "توقع الأفضل، واستعد للأسوأ، واغتنم ما يأتي.",
        "إن آمنت أنك تستطيع، فقد قطعت نصف الطريق.",
        "أفضل طريقة للتنبؤ بالمستقبل هي خلقه.",
        "أنت حدك الوحيد.",
        "حافظ على تركيزك ولا تستسلم أبدًا.",
        "لا تأتي الأشياء العظيمة أبدًا من مناطق الراحة.",
        "إمكانياتك لا حدود لها.",
        "لا تقلل من شأن نفسك، فأنت قادر على تحقيق العجائب.",
        "النجاح رحلة، وليس وجهة.",
        "لا تخشى الفشل، اخشى أن لا تحاول.",
        "اصنع لنفسك طريقاً مليئاً بالنجاح.",
        "أجمل ما في الحياة أن تستمر فيها رغم كل شيء.",
        "ثق بنفسك وبقدراتك ولا تجعل الفشل يثبط عزيمتك.",
        "ابتسم وكن متفائلاً فالحياة جميلة.",
        "لا تتخلى عن حلمك، فالحلم هو بداية كل شيء."
    )
}